JISLJALEQS-EQ: "10397"
MARKSANS-EQ: "10579"
PNB-EQ: "10666"
NUCLEUS-EQ: "10791"
CANBK-EQ: "10794"
GODREJIND-EQ: "10925"
DIVISLAB-EQ: "10940"
IDFCFIRSTB-EQ: "11184"
APOLLO-EQ: "1134"
POONAWALLA-EQ: "11403"
PILANIINVS-EQ: "11445"
EMIL-EQ: "11530"
COFORGE-EQ: "11543"
JBMA-EQ: "11655"
JSWSTEEL-EQ: "11723"
WELCORP-EQ: "11821"
SSWL-EQ: "11829"
JSWHL-EQ: "11880"
YESBANK-EQ: "11915"
ICIL-EQ: "11987"
KAYNES-EQ: "12092"
GSFC-EQ: "1247"
CASTROLIND-EQ: "1250"
TEAMLEASE-EQ: "12716"
KRISHANA-EQ: "12847"
360ONE-EQ: "13061"
PVRINOX-EQ: "13147"
VOLTAMP-EQ: "13577"
AARTIPHARM-EQ: "13868"
BANCOINDIA-EQ: "13880"
TIMKEN-EQ: "14198"
HUBTOWN-EQ: "14203"
HINDZINC-EQ: "1424"
IDEA-EQ: "14366"
PAGEIND-EQ: "14413"
ICRA-EQ: "14523"
KPRMILL-EQ: "14912"
CIEINDIA-EQ: "14937"
CENTUM-EQ: "14982"
TARIL-EQ: "15174"
MANKIND-EQ: "15380"
TARC-EQ: "1581"
INFY-EQ: "1594"
BECTORFOOD-EQ: "1628"
ITC-EQ: "1660"
THYROCARE-EQ: "17032"
CYIENTDLM-EQ: "17187"
VINATIORGA-EQ: "17364"
ADANIPOWER-EQ: "17388"
NHPC-EQ: "17400"
RTNPOWER-EQ: "17520"
QUESS-EQ: "17704"
YATHARTH-EQ: "17738"
JSWENERGY-EQ: "17869"
COHANCE-EQ: "17945"
PERSISTENT-EQ: "18365"
POWERINDIA-EQ: "18457"
NUVAMA-EQ: "18721"
JSWINFRA-EQ: "19020"
KIRLOSIND-EQ: "19025"
KIOCL-EQ: "19126"
ROSSARI-EQ: "19410"
DEEPAKNTR-EQ: "19943"
IREDA-EQ: "20261"
ASHAPURMIN-EQ: "203"
RAMCOCEM-EQ: "2043"
MASTEK-EQ: "2124"
BDL-EQ: "2144"
DIXON-EQ: "21690"
MAXHEALTH-EQ: "22377"
MANORAMA-EQ: "10227"
SYNGENE-EQ: "10243"
FINPIPE-EQ: "1041"
POWERMECH-EQ: "10473"
UCOBANK-EQ: "11223"
IGL-EQ: "11262"
UPL-EQ: "11287"
LUXIND-EQ: "11301"
VAIBHAVGBL-EQ: "11364"
GOKEX-EQ: "11778"
AMBER-EQ: "1185"
NH-EQ: "11840"
HNDFDS-EQ: "12173"
TRIVENI-EQ: "13081"
KEC-EQ: "13260"
GALLANTT-EQ: "13337"
SDBL-EQ: "1338"
RATNAMANI-EQ: "13451"
NSLNISP-EQ: "14180"
PGIL-EQ: "14260"
SEQUENT-EQ: "14296"
PFC-EQ: "14299"
ASTRAL-EQ: "14418"
CSBBANK-EQ: "14966"
BAJAJELEC-EQ: "15034"
AVALON-EQ: "15058"
RELIGARE-EQ: "15068"
ASTERDM-EQ: "1508"
DHANI-EQ: "15384"
TITAGARH-EQ: "15414"
INGERRAND-EQ: "1597"
PRINCEPIPE-EQ: "16045"
IOC-EQ: "1624"
CROMPTON-EQ: "17094"
NESTLEIND-EQ: "17963"
SBICARD-EQ: "17971"
THANGAMAYL-EQ: "18118"
JIOFIN-EQ: "18143"
DIACABS-EQ: "18543"
RRKABEL-EQ: "18566"
PNBHOUSING-EQ: "18908"
SFL-EQ: "19184"
ARVIND-EQ: "193"
KSB-EQ: "1949"
ASHOKA-EQ: "20182"
CGCL-EQ: "20329"
INDIASHLTR-EQ: "20556"
ERIS-EQ: "21154"
ACC-EQ: "22"
EPACK-EQ: "22463"
BANDHANBNK-EQ: "2263"
FACT-EQ: "1008"
FEDERALBNK-EQ: "1023"
UNIONBANK-EQ: "10753"
SHK-EQ: "11212"
JSL-EQ: "11236"
BIOCON-EQ: "11373"
APARINDS-EQ: "11491"
WESTLIFE-EQ: "11580"
LALPATHLAB-EQ: "11654"
PATELENG-EQ: "11699"
JPPOWER-EQ: "11763"
63MOONS-EQ: "11868"
GRANULES-EQ: "11872"
GENUSPOWER-EQ: "11905"
GRASIM-EQ: "1232"
M&MFIN-EQ: "13285"
ALLCARGO-EQ: "13501"
PFOCUS-EQ: "13496"
EMAMILTD-EQ: "13517"
GMRAIRPORT-EQ: "13528"
TECHM-EQ: "13538"
FIEMIND-EQ: "13710"
GESHIP-EQ: "13776"
HINDUNILVR-EQ: "1394"
NFL-EQ: "13925"
GODREJAGRO-EQ: "144"
SANOFI-EQ: "1442"
PHOENIXLTD-EQ: "14552"
AKZOINDIA-EQ: "1467"
PURVA-EQ: "14922"
KNRCON-EQ: "15283"
VGUARD-EQ: "15362"
NESCO-EQ: "15409"
GILLETTE-EQ: "1576"
SUNDROP-EQ: "1663"
BAJAJ-AUTO-EQ: "16669"
HGINFRA-EQ: "1672"
MHRIL-EQ: "17333"
AHLUCONT-EQ: "17833"
BAYERCROP-EQ: "17927"
SBFC-EQ: "18026"
JUBLFOOD-EQ: "18096"
KARURVYSYA-EQ: "1838"
ZAGGLE-EQ: "18608"
MARATHON-EQ: "18659"
KSL-EQ: "18889"
M&M-EQ: "2031"
OBEROIRLTY-EQ: "20242"
AZAD-EQ: "20905"
INNOVACAP-EQ: "21062"
STARCEMENT-EQ: "21091"
JYOTICNC-EQ: "21334"
ABCAPITAL-EQ: "21614"
ICICIGI-EQ: "21770"
TEXRAIL-EQ: "21828"
HFCL-EQ: "21951"
ENTERO-EQ: "22717"
SHAREINDIA-EQ: "104"
RADICO-EQ: "10990"
PPLPHARMA-EQ: "11571"
GUFICBIO-EQ: "11606"
ASTRAMICRO-EQ: "11618"
IIFL-EQ: "11809"
SHOPERSTOP-EQ: "11813"
DCXINDIA-EQ: "11895"
SWSOLAR-EQ: "12489"
GUJALKALI-EQ: "1267"
AMBUJACEM-EQ: "1270"
ROUTE-EQ: "128"
GALAXYSURF-EQ: "1315"
GSPL-EQ: "13197"
SOLARINDS-EQ: "13332"
ELECON-EQ: "13643"
DCBBANK-EQ: "13725"
FLUOROCHEM-EQ: "13750"
NAUKRI-EQ: "13751"
BBL-EQ: "13761"
LTFOODS-EQ: "13816"
SAGCEM-EQ: "14068"
NETWORK18-EQ: "14111"
HSCL-EQ: "14334"
BALAMINES-EQ: "14501"
DLF-EQ: "14732"
IDBI-EQ: "1476"
KDDL-EQ: "14908"
EDELWEISS-EQ: "15119"
COLPAL-EQ: "15141"
INDIAGLYCO-EQ: "1521"
ECLERX-EQ: "15179"
TATAINVEST-EQ: "1621"
APOLLOTYRE-EQ: "163"
JBCHEPHARM-EQ: "1726"
BLS-EQ: "17279"
LLOYDSENGG-EQ: "17801"
GODREJPROP-EQ: "17875"
ABBOTINDIA-EQ: "17903"
KPIL-EQ: "1814"
MANINFRA-EQ: "18226"
LGBBROSLTD-EQ: "18321"
JLHL-EQ: "18553"
SAMHI-EQ: "18614"
STYRENIX-EQ: "19"
MANAPPURAM-EQ: "19061"
PRICOLLTD-EQ: "19631"
LMW-EQ: "1979"
JWL-EQ: "20224"
RESPONIND-EQ: "20323"
COALINDIA-EQ: "20374"
PSPPROJECT-EQ: "20877"
PSB-EQ: "21001"
ASHOKLEY-EQ: "212"
SIS-EQ: "21501"
IEX-EQ: "220"
MRPL-EQ: "2283"
AIIL-EQ: "23553"
AWFIS-EQ: "23864"
CEIGALL-EQ: "24742"
ONGC-EQ: "2475"
PREMIERENE-EQ: "25049"
TDPOWERSYS-EQ: "25178"
WAAREEENER-EQ: "25907"
PCBL-EQ: "2649"
SWIGGY-EQ: "27066"
BLACKBUCK-EQ: "27144"
JUBLINGREA-EQ: "2783"
EASEMYTRIP-EQ: "2792"
VMM-EQ: "27969"
KITEX-EQ: "28899"
TVSHLTD-EQ: "29008"
CARERATING-EQ: "29113"
ONESOURCE-EQ: "29224"
SAIL-EQ: "2963"
HAL-EQ: "2303"
HEIDELBERG-EQ: "2316"
ASIANPAINT-EQ: "236"
RELAXO-EQ: "24225"
EMCURE-EQ: "24398"
NOCIL-EQ: "2442"
LTF-EQ: "24948"
EUREKAFORB-EQ: "25162"
PIDILITIND-EQ: "2664"
KPEL-EQ: "27079"
EIEL-EQ: "27213"
RTNINDIA-EQ: "27297"
LXCHEM-EQ: "2841"
RCF-EQ: "2866"
QPOWER-EQ: "29711"
ORIENTELEC-EQ: "2972"
SUDARSCHEM-EQ: "3327"
TATAELXSI-EQ: "3411"
HONAUT-EQ: "3417"
THERMAX-EQ: "3475"
TITAN-EQ: "3506"
MARICO-EQ: "4067"
SHRIRAMFIN-EQ: "4306"
SBCL-EQ: "4656"
BLUEDART-EQ: "495"
SHARDACROP-EQ: "4992"
GMDCLTD-EQ: "5204"
ALIVUS-EQ: "5265"
AAVAS-EQ: "5385"
CARTRADE-EQ: "5407"
SERVOTECH-EQ: "5507"
CANFINHOME-EQ: "583"
SANSERA-EQ: "5751"
GRAPHITE-EQ: "592"
NATIONALUM-EQ: "6364"
CIPLA-EQ: "694"
HEMIPROP-EQ: "701"
GANECOS-EQ: "6944"
JTLIND-EQ: "7287"
AVANTIFEED-EQ: "7936"
DCMSHRIRAM-EQ: "811"
CHALET-EQ: "8546"
ANUP-EQ: "9014"
METROPOLIS-EQ: "9581"
JAYNECOIND-EQ: "2331"
NEULANDLAB-EQ: "2406"
RPEL-EQ: "24735"
SHAKTIPUMP-EQ: "25574"
JISLDVREQS-EQ: "25684"
PFIZER-EQ: "2643"
SWANENERGY-EQ: "27095"
NIVABUPA-EQ: "27097"
AUROPHARMA-EQ: "275"
GICRE-EQ: "277"
RALLIS-EQ: "2816"
IKS-EQ: "28125"
CRAFTSMAN-EQ: "2854"
INDUSTOWER-EQ: "29135"
MOSCHIP-EQ: "29459"
KALYANKJIL-EQ: "2955"
NAZARA-EQ: "2987"
PRABHA-EQ: "30134"
JINDALSAW-EQ: "3024"
VEDL-EQ: "3063"
TIINDIA-EQ: "312"
HONDAPOWER-EQ: "3138"
SUBROS-EQ: "3324"
BALMLAWRIE-EQ: "338"
SUNFLAG-EQ: "3348"
SURYAROSNI-EQ: "3375"
VIPIND-EQ: "3703"
BATAINDIA-EQ: "371"
TATACOMM-EQ: "3721"
ZEEL-EQ: "3812"
BERGEPAINT-EQ: "404"
NATCOPHARM-EQ: "3918"
GULFOILLUB-EQ: "4391"
MPHASIS-EQ: "4503"
EPIGRAL-EQ: "5382"
CESC-EQ: "628"
LATENTVIEW-EQ: "6818"
AARTIIND-EQ: "7"
MEDPLUS-EQ: "7254"
NPST-EQ: "756324"
OSWALPUMPS-EQ: "756802"
NBCC-EQ: "31415"
LODHA-EQ: "3220"
ISGEC-EQ: "3329"
TORNTPHARM-EQ: "3518"
VOLTAS-EQ: "3718"
WIPRO-EQ: "3787"
BEL-EQ: "383"
CAPLIPOINT-EQ: "3906"
BANKBARODA-EQ: "4668"
3MINDIA-EQ: "474"
SHYAMMETL-EQ: "4693"
BIRLACORPN-EQ: "480"
BOMDYEING-EQ: "513"
APTUS-EQ: "5435"
ASTRAZEN-EQ: "5610"
INTELLECT-EQ: "5926"
SOUTHBANK-EQ: "5948"
STAR-EQ: "7374"
RAJESHEXPO-EQ: "7401"
WOCKPHARMA-EQ: "7506"
WAAREERTL-EQ: "756038"
CRISIL-EQ: "757"
AEGISVOPAK-EQ: "757336"
DIGITIDE-EQ: "757515"
KTKBANK-EQ: "8054"
DALBHARAT-EQ: "8075"
DEEPAKFERT-EQ: "827"
EIDPARRY-EQ: "916"
ARVINDFASN-EQ: "9111"
ELECTCAST-EQ: "928"
SKIPPER-EQ: "9428"
DELHIVERY-EQ: "9599"
HAVELLS-EQ: "9819"
NEOGEN-EQ: "9917"
GOPAL-EQ: "23066"
SANDHAR-EQ: "2397"
PIIND-EQ: "24184"
VADILALIND-EQ: "24196"
VSTTILLERS-EQ: "24292"
BANSALWIRE-EQ: "24386"
OLAELEC-EQ: "24777"
ADANIENT-EQ: "25"
WINDMACHIN-EQ: "24969"
RAYMONDLSL-EQ: "25073"
PGEL-EQ: "25358"
POLYMED-EQ: "25718"
LLOYDSENT-EQ: "25807"
AVL-EQ: "25984"
PRECWIRE-EQ: "2717"
NTPCGREEN-EQ: "27176"
SANATHAN-EQ: "28805"
AGARWALEYE-EQ: "29452"
E2E-EQ: "8937"
DPABHUSHAN-EQ: "936"
RAINBOW-EQ: "9408"
LICI-EQ: "9480"
WONDERLA-EQ: "3002"
RHIM-EQ: "31163"
BALKRISIND-EQ: "335"
SUNDRMFAST-EQ: "3345"
BALRAMCHIN-EQ: "341"
BASF-EQ: "368"
RITES-EQ: "3761"
AEGISLOG-EQ: "40"
VARROC-EQ: "3857"
HERITGFOOD-EQ: "4598"
INDRAMEDCO-EQ: "4751"
ICICIBANK-EQ: "4963"
CLEAN-EQ: "5049"
GRINFRA-EQ: "5054"
KPIGREEN-EQ: "5108"
UTIAMC-EQ: "527"
ITDCEM-EQ: "5622"
CUB-EQ: "5701"
BHAGCHEM-EQ: "6164"
CHAMBLFERT-EQ: "637"
NYKAA-EQ: "6545"
BSOFT-EQ: "6994"
ANANDRATHI-EQ: "7145"
DATAPATTNS-EQ: "7358"
THELEELA-EQ: "757014"
DALMIASUG-EQ: "781"
ALEMBICLTD-EQ: "79"
AWL-EQ: "8110"
GMRP&UI-EQ: "8529"
NLCINDIA-EQ: "8585"
PRIVISCL-EQ: "8825"
HIKAL-EQ: "9668"
EMUDHRA-EQ: "9756"
ARE&M-EQ: "100"
SCHAEFFLER-EQ: "1011"
ZENSARTECH-EQ: "1076"
SYRMA-EQ: "10793"
GABRIEL-EQ: "1085"
WELSPUNLIV-EQ: "11253"
JAIBALAJI-EQ: "11256"
LT-EQ: "11483"
NEWGEN-EQ: "1164"
GLAND-EQ: "1186"
JKPAPER-EQ: "11860"
AURIONPRO-EQ: "12022"
ACI-EQ: "12024"
HEROMOTOCO-EQ: "1348"
JMFINANCIL-EQ: "13637"
AGI-EQ: "1412"
TIIL-EQ: "14223"
V2RETAIL-EQ: "14766"
CENTRALBK-EQ: "14894"
RBA-EQ: "1494"
MOTILALOFS-EQ: "14947"
POWERGRID-EQ: "14977"
ADANIPORTS-EQ: "15083"
KOLTEPATIL-EQ: "15124"
HCG-EQ: "15555"
UBL-EQ: "16713"
PATANJALI-EQ: "17029"
PREMEXPLN-EQ: "17397"
POKARNA-EQ: "17651"
ALOKINDS-EQ: "17675"
SARDAEN-EQ: "17758"
DBREALTY-EQ: "18124"
RBLBANK-EQ: "18391"
ENDURANCE-EQ: "18822"
VBL-EQ: "18921"
ITDC-EQ: "19299"
BSE-EQ: "19585"
TRENT-EQ: "1964"
HONASA-EQ: "19813"
ASKAUTOLTD-EQ: "20152"
WABAG-EQ: "20188"
IRFC-EQ: "2029"
TATATECH-EQ: "20293"
INDIGOPNTS-EQ: "2048"
HOMEFIRST-EQ: "2056"
DOMS-EQ: "20551"
JINDWORLD-EQ: "20642"
VTL-EQ: "2073"
HUDCO-EQ: "20825"
MAHSCOOTER-EQ: "2085"
CDSL-EQ: "21174"
AUBANK-EQ: "21238"
MEDIASSIST-EQ: "21705"
SUNDARMHLD-EQ: "2183"
SBILIFE-EQ: "21808"
UNITDSPR-EQ: "10447"
SHARDAMOTR-EQ: "10530"
KRBL-EQ: "10577"
FOSECOIND-EQ: "1073"
NSIL-EQ: "11239"
GHCL-EQ: "1127"
PETRONET-EQ: "11351"
PTC-EQ: "11355"
WELENT-EQ: "11626"
GODFRYPHLP-EQ: "1181"
GOLDIAM-EQ: "11971"
RENUKA-EQ: "12026"
JKCEMENT-EQ: "13270"
HDFCBANK-EQ: "1333"
CENTURYPLY-EQ: "13305"
KKCL-EQ: "13381"
GPIL-EQ: "13409"
RSYSTEMS-EQ: "13414"
JKLAKSHMI-EQ: "13491"
HINDALCO-EQ: "1363"
IRCTC-EQ: "13611"
HBLENGINE-EQ: "13966"
JASH-EQ: "13982"
LUMAXTECH-EQ: "14014"
UNOMINDA-EQ: "14154"
FINCABLES-EQ: "1038"
ARVSMART-EQ: "10457"
UFLEX-EQ: "1053"
MPSLTD-EQ: "10578"
BHARTIARTL-EQ: "10604"
MARUTI-EQ: "10999"
INDIGO-EQ: "11195"
AFFLE-EQ: "11343"
ULTRACEMCO-EQ: "11532"
FORCEMOT-EQ: "11573"
NTPC-EQ: "11630"
ALKEM-EQ: "11703"
BIKAJI-EQ: "11966"
RUSTOMJEE-EQ: "12219"
GREAVESCOT-EQ: "1235"
ABB-EQ: "13"
IIFLCAPS-EQ: "13072"
AIAENG-EQ: "13086"
GRINDWELL-EQ: "13560"
ACE-EQ: "13587"
ANANTRAJ-EQ: "13620"
SOBHA-EQ: "13826"
HINDPETRO-EQ: "1406"
SIYSIL-EQ: "14096"
FSL-EQ: "14304"
INDIANB-EQ: "14309"
FORTIS-EQ: "14592"
INDIACEM-EQ: "1515"
KIRLPNU-EQ: "15180"
RAIN-EQ: "15337"
LINDEINDIA-EQ: "1627"
IPCALAB-EQ: "1633"
RPGLIFE-EQ: "16725"
ZFCVINDIA-EQ: "16915"
AJMERA-EQ: "17307"
NETWEB-EQ: "17433"
ZYDUSWELL-EQ: "17635"
SUNTECK-EQ: "17641"
KAJARIACER-EQ: "1808"
TVSSCS-EQ: "18151"
TCPLPACK-EQ: "184"
HPL-EQ: "18679"
SIGNATURE-EQ: "18743"
CUMMINSIND-EQ: "1901"
TI-EQ: "19196"
MAXESTATES-EQ: "19646"
GANESHHOUC-EQ: "14339"
SPARC-EQ: "14788"
IFBIND-EQ: "1485"
CERA-EQ: "15039"
JYOTHYLAB-EQ: "15146"
CEATLTD-EQ: "15254"
JKIL-EQ: "15266"
IRB-EQ: "15313"
NMDC-EQ: "15332"
RECLTD-EQ: "15355"
INFIBEAM-EQ: "16249"
PTCIL-EQ: "16682"
SUMICHEM-EQ: "17105"
SHRIPISTON-EQ: "17186"
LLOYDSME-EQ: "17313"
LTIM-EQ: "17818"
DBCORP-EQ: "17881"
ADVENZYMES-EQ: "18039"
CONCORDBIO-EQ: "18060"
DBL-EQ: "18086"
LTTS-EQ: "18564"
BLUEJET-EQ: "19686"
CELLO-EQ: "19795"
MASFIN-EQ: "199"
DMART-EQ: "19913"
RAMKY-EQ: "20134"
PRESTIGE-EQ: "20302"
FEDFINA-EQ: "20322"
MAHSEAMLES-EQ: "2088"
HAPPYFORGE-EQ: "20854"
SUNCLAY-EQ: "20956"
GODREJCP-EQ: "10099"
ADANIENSOL-EQ: "10217"
LUPIN-EQ: "10440"
GUJGASLTD-EQ: "10599"
INDIAMART-EQ: "10726"
MAHABANK-EQ: "11377"
GIPCL-EQ: "1145"
GNFC-EQ: "1174"
FMGOETZE-EQ: "1190"
MEDANTA-EQ: "11956"
NITCO-EQ: "13300"
KEI-EQ: "13310"
HEG-EQ: "1336"
KFINTECH-EQ: "13359"
GREENPANEL-EQ: "13810"
TANLA-EQ: "13976"
PITTIENG-EQ: "14134"
JKTYRE-EQ: "14435"
EMBDL-EQ: "14450"
GOKULAGRO-EQ: "14480"
WEBELSOLAR-EQ: "14602"
NAVINFLUOR-EQ: "14672"
TIMETECHNO-EQ: "14707"
INDHOTEL-EQ: "1512"
UJJIVANSFB-EQ: "15228"
GMMPFAUDLR-EQ: "1570"
IONEXCHANG-EQ: "1630"
KIRIINDUS-EQ: "16639"
BAJAJFINSV-EQ: "16675"
ITI-EQ: "1675"
REFEX-EQ: "17764"
NIITMTS-EQ: "17747"
WHIRLPOOL-EQ: "18011"
SANDUMA-EQ: "18359"
ICICIPRULI-EQ: "18652"
SJVN-EQ: "18883"
KINGFA-EQ: "18944"
KOTAKBANK-EQ: "1922"
BAJAJCON-EQ: "19531"
GRAVITA-EQ: "20534"
INOXINDIA-EQ: "20607"
PENIND-EQ: "20621"
TCI-EQ: "10580"
OLECTRA-EQ: "10637"
OFSS-EQ: "10738"
TMB-EQ: "10945"
GARFIBRES-EQ: "1100"
HARSHA-EQ: "11162"
RKFORGE-EQ: "11411"
DATAMATICS-EQ: "11423"
CCL-EQ: "11452"
GLAXO-EQ: "1153"
TCS-EQ: "11536"
SUPRAJIT-EQ: "11689"
KANSAINER-EQ: "1196"
SUZLON-EQ: "12018"
FIVESTAR-EQ: "12032"
MBAPL-EQ: "12686"
SAFARI-EQ: "13035"
SUNTV-EQ: "13404"
SKYGOLD-EQ: "13631"
TORNTPOWER-EQ: "13786"
REDINGTON-EQ: "14255"
IFCI-EQ: "1491"
KSCL-EQ: "14972"
MANGCHEFER-EQ: "15007"
BRIGADE-EQ: "15184"
APOLLOHOSP-EQ: "157"
GVT&D-EQ: "16783"
SINDHUTRAD-EQ: "16859"
SENCO-EQ: "17271"
OIL-EQ: "17438"
MGL-EQ: "17534"
REDTAPE-EQ: "17859"
HINDCOPPER-EQ: "17939"
MMTC-EQ: "17957"
KIRLOSBROS-EQ: "18581"
EMSLIMITED-EQ: "18593"
LAURUSLABS-EQ: "19234"
IMFA-EQ: "19235"
BOROLTD-EQ: "19401"
GPPL-EQ: "19731"
LICHSGFIN-EQ: "1997"
LUMAXIND-EQ: "2018"
CHENNPETRO-EQ: "2049"
JAMNAAUTO-EQ: "20778"
MOIL-EQ: "20830"
KIRLOSENG-EQ: "20936"
TEJASNET-EQ: "21131"
OPTIEMUS-EQ: "21469"
PARKHOTELS-EQ: "22649"
MFSL-EQ: "2142"
COCHINSHIP-EQ: "21508"
CHOLAHLDNG-EQ: "21740"
BOSCHLTD-EQ: "2181"
MOREPENLAB-EQ: "2259"
JSFB-EQ: "22663"
MRF-EQ: "2277"
MUTHOOTFIN-EQ: "23650"
GODIGIT-EQ: "23799"
ARKADE-EQ: "25398"
KRN-EQ: "25643"
HYUNDAI-EQ: "25844"
LEMONTREE-EQ: "2606"
ACMESOLAR-EQ: "27061"
RAYMOND-EQ: "2859"
PCJEWELLER-EQ: "29124"
AJAXENGG-EQ: "29624"
HEXT-EQ: "29666"
ORIENTCEM-EQ: "30089"
SHANTIGEAR-EQ: "3078"
INDOSTAR-EQ: "3088"
BORORENEW-EQ: "3149"
JTEKTINDIA-EQ: "3237"
SRF-EQ: "3273"
SUNDARMFIN-EQ: "3339"
SUNPHARMA-EQ: "3351"
SMLISUZU-EQ: "3387"
TATAPOWER-EQ: "3426"
BANARISUG-EQ: "350"
ADANIGREEN-EQ: "3563"
UNICHEMLAB-EQ: "3579"
JUBLPHARMA-EQ: "3637"
VESUVIUS-EQ: "3676"
VSTIND-EQ: "3724"
WSTCSTPAPR-EQ: "3799"
BHARATRAS-EQ: "3834"
MOTHERSON-EQ: "4204"
HDFCAMC-EQ: "4244"
AARTIDRUGS-EQ: "4481"
ALKYLAMINE-EQ: "4487"
SONACOMS-EQ: "4684"
FDC-EQ: "4898"
IRCON-EQ: "4986"
ETERNAL-EQ: "5097"
CIGNITITEC-EQ: "5142"
INDUSINDBK-EQ: "5258"
PDSL-EQ: "5264"
BRITANNIA-EQ: "547"
J&KBANK-EQ: "5633"
TECHNOE-EQ: "6445"
GOCOLORS-EQ: "6964"
COROMANDEL-EQ: "739"
SUPRIYA-EQ: "7390"
ZENTEC-EQ: "7508"
ELLEN-EQ: "758563"
IMAGICAA-EQ: "7672"
SHAILY-EQ: "8727"
ELGIEQUIP-EQ: "937"
CAMPUS-EQ: "9362"
PGHL-EQ: "940"
ESCORTS-EQ: "958"
RVNL-EQ: "9552"
INDGN-EQ: "23693"
AADHARHFC-EQ: "23729"
IXIGO-EQ: "24067"
DHANUKA-EQ: "24409"
FIRSTCRY-EQ: "24814"
BAJAJHFL-EQ: "25270"
MINDACORP-EQ: "25897"
AFCONS-EQ: "25977"
TRANSRAILL-EQ: "28714"
MTNL-EQ: "2294"
NCC-EQ: "2319"
AKUMS-EQ: "24715"
IGIL-EQ: "28378"
VMART-EQ: "29284"
PROTEAN-EQ: "29472"
SAMMAANCAP-EQ: "30125"
BAJAJHLDNG-EQ: "305"
SCI-EQ: "3048"
SIEMENS-EQ: "3150"
TATACHEM-EQ: "3405"
BBTC-EQ: "380"
BHARATFORG-EQ: "422"
BHEL-EQ: "438"
HDFCLIFE-EQ: "467"
GAIL-EQ: "4717"
DODLA-EQ: "4822"
MAZDOCK-EQ: "509"
BPCL-EQ: "526"
ROLEXRINGS-EQ: "5279"
DEVYANI-EQ: "5373"
VIJAYA-EQ: "5585"
ATGL-EQ: "6066"
ABREL-EQ: "625"
PAYTM-EQ: "6705"
JINDALSTEL-EQ: "6733"
STARHEALTH-EQ: "7083"
MAPMYINDIA-EQ: "7227"
ATHERENERG-EQ: "757645"
CMSINFO-EQ: "7603"
MAHLIFE-EQ: "8050"
RPSGVENT-EQ: "8119"
CHOICEIN-EQ: "8866"
POLYCAB-EQ: "9590"
SPLPETRO-EQ: "9617"
KPITTECH-EQ: "9683"
BAJAJHIND-EQ: "308"
MCX-EQ: "31181"
ANGELONE-EQ: "324"
SKFINDIA-EQ: "3186"
SUPREMEIND-EQ: "3363"
SWARAJENG-EQ: "3384"
TATACONSUM-EQ: "3432"
THOMASCOOK-EQ: "3481"
TTKPRESTIG-EQ: "3546"
BEML-EQ: "395"
NIACL-EQ: "399"
GREENPLY-EQ: "3987"
JCHAC-EQ: "4491"
CONCOR-EQ: "4749"
HAPPSTMNDS-EQ: "48"
SAREGAMA-EQ: "4892"
CYIENT-EQ: "5748"
VISHNU-EQ: "6908"
TEGA-EQ: "7105"
COSMOFIRST-EQ: "742"
GLENMARK-EQ: "7406"
BELRISE-EQ: "757102"
AJANTPHARM-EQ: "8124"
MANYAVAR-EQ: "8167"
BLUESTARCO-EQ: "8311"
DRREDDY-EQ: "881"
MSTCLTD-EQ: "9356"
PNCINFRA-EQ: "9385"
PRUDENT-EQ: "9553"
TRIDENT-EQ: "9685"
PARADEEP-EQ: "9741"
EPL-EQ: "981"
ETHOSLTD-EQ: "9750"
HLEGLAS-EQ: "2289"
NAVNETEDUL-EQ: "2385"
RAILTEL-EQ: "2431"
ABDL-EQ: "24308"
MAITHANALL-EQ: "24538"
MIDHANI-EQ: "2463"
PNGJL-EQ: "25312"
SANOFICONR-EQ: "25222"
PGHH-EQ: "2535"
ATUL-EQ: "263"
POLYPLEX-EQ: "2687"
PRAJIND-EQ: "2705"
SAGILITY-EQ: "27052"
PRSMJOHNSN-EQ: "2739"
SAILIFE-EQ: "27839"
VENTIVE-EQ: "28847"
ABFRL-EQ: "30108"
SBIN-EQ: "3045"
CAMS-EQ: "342"
NAM-INDIA-EQ: "357"
TATAMOTORS-EQ: "3456"
FINEORG-EQ: "3744"
HATSUN-EQ: "3892"
NAVA-EQ: "4014"
DYNAMATECH-EQ: "4525"
BANKINDIA-EQ: "4745"
KIMS-EQ: "4847"
NUVOCO-EQ: "5426"
CHEMPLASTS-EQ: "5449"
GRSE-EQ: "5475"
PARAS-EQ: "5911"
GOODLUCK-EQ: "6125"
FCL-EQ: "6198"
SONATSOFTW-EQ: "6596"
SJS-EQ: "6643"
EXIDEIND-EQ: "676"
SAPPHIRE-EQ: "6718"
CHOLAFIN-EQ: "685"
RATEGAIN-EQ: "7177"
JUNIPER-EQ: "22824"
BHARTIHEXA-EQ: "23489"
TBOTEK-EQ: "23740"
PEL-EQ: "2412"
SYMPHONY-EQ: "24190"
ASHIANA-EQ: "24403"
AVANTEL-EQ: "24610"
APLLTD-EQ: "25328"
NORTHARC-EQ: "25426"
TRITURBINE-EQ: "25584"
APLAPOLLO-EQ: "25780"
MTARTECH-EQ: "2709"
ANURAS-EQ: "2829"
RELIANCE-EQ: "2885"
ITCHOTELS-EQ: "29251"
MCLOUD-EQ: "29482"
GUJTHEM-EQ: "29731"
JUSTDIAL-EQ: "29962"
SHREECEM-EQ: "3103"
BAJFINANCE-EQ: "317"
TATASTEEL-EQ: "3499"
CREDITACC-EQ: "4421"
ENGINERSIN-EQ: "4907"
ASAHIINDIA-EQ: "5378"
ACUTAAS-EQ: "5578"
CARBORUNIV-EQ: "595"
AXISBANK-EQ: "5900"
ABSLAMC-EQ: "6018"
POLICYBZR-EQ: "6656"
GREENLAM-EQ: "6848"
HCLTECH-EQ: "7229"
METROBRAND-EQ: "7242"
CGPOWER-EQ: "760"
KALPATARU-EQ: "758558"
DABUR-EQ: "772"
INOXWIND-EQ: "7852"
ZYDUSLIFE-EQ: "7929"
GATEWAY-EQ: "8510"
USHAMART-EQ: "8840"
EQUITASBNK-EQ: "913"
ORCHPHARMA-EQ: "926"
TIPSMUSIC-EQ: "9117"
STLTECH-EQ: "9309"
AETHER-EQ: "9810"
GRWRHITECH-EQ: "7982"
TVSMOTOR-EQ: "8479"
MSUMI-EQ: "8596"
VRLLOG-EQ: "8696"
GAEL-EQ: "8828"
EICHERMOT-EQ: "910"
EIHOTEL-EQ: "919"
IOB-EQ: "9348"
ESABINDIA-EQ: "955"
VENUSPIPES-EQ: "9592"